appointments validation
appointus/appointus-node-api pull request #13
Opened 2019-07-07 07:57 UTC by nintendaii

Modules used:
-@hapi/joi
-@hapi/joi-date
-moment

2019-07-07 10:12 UTC, user4i requested changes

2019-07-07 10:12 UTC, user4i commented on main.js
> +app.use(function(req, res, next) {
Please use cors package for 9-14 lines

2019-07-07 10:12 UTC, user4i commented on package.json
> +    "@hapi/joi": "^15.1.0",
use moment for it not @hapi/joi, @hapi/joi-date

2019-07-07 10:25 UTC, user4i requested changes

2019-07-07 10:25 UTC, user4i commented on routes/appointments.js
> +  if (currentDate > req.body.date || (currentDate == req.body.date && currentTime > req.body.time))
And what about moment.isAfter, moment.isBefore?

2019-07-08 18:53 UTC, nintendaii commented on main.js
> +app.use(function(req, res, next) {
done

2019-07-10 19:56 UTC, merged